import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import { cookies } from 'next/headers';
import { verifyToken } from '@/lib/utils';
import { decodeToken } from '@/lib/utils';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = await cookies()
  const token = cookieStore.get('token')?.value
  let isAuthenticated = false
  let decoded = undefined
  if (token) {
    isAuthenticated = verifyToken(token)
    decoded = decodeToken(token) as { email: string, name: string }
  }

  //token ? await verifyToken() : false

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        {isAuthenticated && decoded && decoded.name && <Navbar name={decoded.name} />}
        {children}
      </body>
    </html>
  );
}
